cloudflare_tunnel_token: ENC[AES256_GCM,data:la2uk0XFwDJ45orf7Gz0FYs7MzU+W1cCYUBXvk9NdMeelevccizMAxNYM6c2N+oOMHSNMiE1C+9/jo69sGFh9k70uHTb6StFXPUOpZSXi7NlZnHGZ80dLb9shjErP2Y0lyjCXxuowtwSavuZZo7SiiWc+4jcGUJAhowoRWL/BDJYOGYhIvfnDgM3sYMw7DJ5Z96T4x9g5Y5PLrIclTuzE0FzslwHb2XeQVJQH12BxhIeeAGX,iv:3SqPxfhUwLGHnzyLqrlVqJRWwy/OtxZrJXIr6CP6YlU=,tag:kyjYnfiNoalvYfuoapE0ww==,type:str]
sops:
    age:
        - recipient: age1kfklkd3xuacvfu0gy35v7cwk5lw8y9xv0lr5hs2ddyn82ww9mdlslfth6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVmFkS0pjVlNVSmpQNlFq
            dFpiZWhhZW1USG1XcXVQdzVGNE5LTXlEVUMwCnpqSUVPVmZJenN2S3l1OUdHS285
            SEQ2dE1tSzFKblZlS2cyem9ZTjR6VFUKLS0tIGsyeXA5dFZ2RkZXK2JZYVV0Lzkv
            RUJZOXNMSjNGeG1mbzEyOG5GSUxZdUkKsOke0KzFdmCkWlMWxF2gPHboMOXeHROS
            Okv7SYmlXPySspSvD24wM7BFHCSi31NrmA6iaTnoLeIELQwuChDNYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T11:22:10Z"
    mac: ENC[AES256_GCM,data:FA6fZQt4m/MC3pKwKlYixWZElAWBtOsxLmBC3W7EZ+8k3JGFsQoEAhZHL2ENpTxbLvwq/bBC9vEq16mT1HvPdjoQi2rojC0LiHY+GH8KJYPzLWWF10zP/ezBkzuVfbnTPAonJLwAdXhsxmAnDz73qyX/8XiTyCU9HeZVcjfuFJ0=,iv:EWSO312yW46d8ANfRz+a/Ztv1dzV/r6JOlErP7rpYgA=,tag:IEWWGaHJcqegymsfgf3IYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
