protonvpn_wg_conf: ENC[AES256_GCM,data:8EFlwb+BAKjvTbtMFmOapMG+c4Ke6pAWm037JOh5+EQbCaPhbjZxjqqjmFQOFyr+EMXnm9b/9/Wp2xjXCuUiGwxlpfNglFM4mrrboXt5MqwigXQs9YGtyOC9o8TAG6gWKE4zJL5b7o5I9viUzFP5FYJLcOhilva+gij40wKO4lKW/vzXVEJxu4FCLY7/Ox4ZwsdwGNsyKcOI0X6txj5DwGJl2nyLY7pskARbkHZB1aoDhRrOWRSsvCQA4zGIVKMqd1cMrHLkR6R8ZZBfLXhZzWqndrN4HcTSuygWjlyoLpy5pY89/f4NEUdgkfnHck6JLmntr+rjilZdKMG87ZRjxbTUbakMIp9MeFi0RXmgXgTjeQOq5hoOFgO0Ga+Ep5gN2/Tpf608UJ184TzpXEsb70AqqSfoUfeSWd1Hge0fnU0g2DuqrA2gz7thggqvh+jLQZ61+KIjptdIwd3qb+wMQquqy8LJbdxgLwHdmA+jrUwiEk+J,iv:W6UWT9aUA1cmb/BFDKyJVxcETMJLcIYUZ1EU1PEksOQ=,tag:9liXdGavJiaCqRJGV2MUSQ==,type:str]
qbittorrent_webui_password: ENC[AES256_GCM,data:16v+dtrwoIU=,iv:CwnfJCC3VujL4R6aH3MU+GVuBMQHra2GQ3m60NECEs8=,tag:pS8NQjWs2bIoOxd5H9lUQQ==,type:str]
sops:
    age:
        - recipient: age1kfklkd3xuacvfu0gy35v7cwk5lw8y9xv0lr5hs2ddyn82ww9mdlslfth6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNjYrWGdIa09FaFA2QTlE
            V2tTeld6VnpoYTNkakhnYmx6MGtLZVdFUmw0CkNTbER3MjJ2QW5rRWxWZmEvSXA1
            Zko1VTlmeU91NytJbEhSQ2ltanRkTTAKLS0tIEVESFErU1ZYUytBQ3dDY05nbEVW
            OWJjY1JacGVzZzRRTVorQm8wOWd0V2cKck0ekOOoGSgsqxFrN2eQ/L095BKF6iYw
            1JQjVXpaCi7Xy24VvVzPvqtqtzGsoaXvri5m/3GR+e/db/bPtaTCAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T08:56:39Z"
    mac: ENC[AES256_GCM,data:xGzco0TYTWc1HQIp7zl+MTplcBuP5DdQU8EuRJ3zcWrkPKJ4O7j8SzZbx2gOve8XyGh7C0L+/0kH51G1NelXlhbGuWtagIV9Xmsu5Dd4EhlRT96Vwl+Tjupc0gYkHKZZlU7dchwvjotYwI4g1nAt1pIqYB9F9BxEaI5ixs/1QP8=,iv:djZhAuUJB+mCDi0u/xRCd3hLxTtbCoVFDqxOEikPVRk=,tag:W2W5UIZEsVbEz4XUWwG58Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
