cloudflare_tunnel_token: ENC[AES256_GCM,data:sISg+5NpZFq4tXHTa6CWmd9JbeCqpzVLCqSFxqjrOr+y+37ov5TrWFiiQaKha5AU7yVeyDFs6lKoQJPSekT3juQ7bOmX27l0Ya45oZdsijAvMH+jGlPIQ+OlDVrJ7j/RTzsqAEGZ7KsXB81+deYM057VQf8Ng+xvGxSE2m0ZiwlbRGqILON3wOAINR7CdvQEc/veR2t4wUdgyO27+WRN18SVIup+C1P00uu9eCsvw/gAPrLp,iv:WdBb3GLUdD+s444u0P2AOmKAvFTlHrHxiYMZRwB0pb8=,tag:mcRquGCRbeqed2l5Zb2Y4A==,type:str]
immich_db_password: ENC[AES256_GCM,data:bp+NaZgHMfplAvVBdc/lF9m1jgzkNHFLCM808+VQoFw=,iv:bm7O5D4HEG1WvumSAuqXWBKkWNRImV3Y6Fx/v0DzMZA=,tag:su4X1x0/jhkZVmBLNe8Uog==,type:str]
sops:
    age:
        - recipient: age1kfklkd3xuacvfu0gy35v7cwk5lw8y9xv0lr5hs2ddyn82ww9mdlslfth6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVB6STZrVTloc3JvVEJn
            NDZQOTAyTzlGZjl1RUpIRTQ1Sjl4bjYxcFJzCldiTk10dFUwdW5OVVhZSnhLS2Fk
            Ly9sNUFpR1VWaElxck5TeWlpRENRa3cKLS0tIE5DK1VuSmpPY2Foam5HWk41SEl1
            NDVSWDVpOHZMVmxWTHB3Q25maGZ5NXcKbDYzx0NNZhXi1N4kyBisJImK7toLoNOG
            DAsrgy4cbNHmxRpt3TpaHgy02atXjjFtH0HTxalN5De2RLAGdjE9Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T10:41:23Z"
    mac: ENC[AES256_GCM,data:/VLDaEBvpRn0j9qSvNZ1qMI7eImd7KzzvbPlr4cBuacncpQCIoHkbTZPJOr2NwV+P8g/BgpQiYOlhpamsqe5kj8urEnIyqvB6Xg4ZR7URqqg4Jjv91SfkJMsjHhUG4As873YScr8gUxYq1Jl9VigywA5O5TVxQQUlAUH9+u7pWk=,iv:IumuVN6uMq/++33m8xWqldfsjTp3M9QLrXaICYW4SE0=,tag:bsBdGiT2ueF4OtR0oKIcEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
