cloudflare_tunnel_token: ENC[AES256_GCM,data:bMx/SqqLSxmEolVEs+i0ggi8JZtzETuwRnO2D9gZ7UNONayueiy1O0loMmxlWJCktD+qrafAQrqi4TVA9C9ZjpuYjCZVe2QwoCM3xjU/RBoCh2ZIsBHylqt2qhxxbrGaPCPEVq8Fc7EkewFEScTkLEb1f36vCP7T3unzYrhauL9mC+3UMumJEo1jekEiLaTJeTvf5pErm+4+sFdrHrxKh1NmicddtKCHFiDCf7DVGo+GnyHy,iv:rjp+E1gnO8kEWiqlf2YWk86NKGN/WH0pB+sk7BYL/yE=,tag:C4OqigIKKiWX+E2NpMC50w==,type:str]
immich_db_password: ENC[AES256_GCM,data:IM02dCG3gKz6Br5QGqcKltnA2PRTp9pYqFDV3dxixK8=,iv:RF7TtZi7hp8kis3qdmDhT7R5iJuAN9NRiXnKfeyi6RM=,tag:kvuNnhKwEB0fxtA2d6HCEw==,type:str]
paperless_db_password: ENC[AES256_GCM,data:xyYadpK1xTAkmXltxhuyC3XbadfHRM5ignGQo1r7TXxpN0Ll30ZXMaKXozQ=,iv:c8M/kRr4ixFvvvwZA4Qj0U9UzdAiD+EpyqQDU7h6pnk=,tag:SvggfXB2sCvU32ln1+mfqQ==,type:str]
paperless_secret_key: ENC[AES256_GCM,data:xnjLwdDz63ziKKRlIQSeqXYl/vCm2ULYRGJuZCowCmvBU1EOqrqCJK6dBHycTQUtejUE1jTEjVeWR/NFrexQFcgU96oSv7eJTvpACF9VhbpXDw3LdFEQSA==,iv:3whbwBwu/Zc9CNYfPlj2n0uDyqUQlBtlSLmCaLm3JCQ=,tag:5gamYB3+e2kbq+lgP6TrsA==,type:str]
paperless_admin_user: ENC[AES256_GCM,data:y3omvAS9ARs=,iv:+4GoTxy9UubolIQut1Snc3DYDSwsYomgvCugCKoGT3M=,tag:pH32+uaHIhNZ8MmULtDRTg==,type:str]
paperless_admin_password: ENC[AES256_GCM,data:d5ELf6EdU7IlmqXfO4h1/9Slneb86yjS/cnkZ56W94meZWCwgyC+W4B5l8I=,iv:8qkBp7h15FlDR/8yk2iZTwP8P9i7s6GqP2Vp42V9og8=,tag:6OaG/2gZNtMTMmnLpRg82g==,type:str]
sops:
    age:
        - recipient: age1kfklkd3xuacvfu0gy35v7cwk5lw8y9xv0lr5hs2ddyn82ww9mdlslfth6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYclQ0WFMrNUw5Q0NIS3c4
            STFvT0R5N3Q3L1ZqMkduZ3I0VnBaZzVHOW5VCitKSWNVZ1NJOUxKY3k4REdwVmVB
            Sk9RU0dHbmpuVU1zWkU5eFUxWUJGcFEKLS0tIDRua1o1U2hqRHpkTjNrWHZOb0Er
            OVI4QjlCOS96ci9kSmxJUm1zUFpyVUkKJoDt+jh9CsQKjCWw3Sk/4GLXZd7LP8EQ
            Yp5czq0ROkkqSUUrKXSOUClOyKn/a2iORo7uro7ClqqFMmC2O04CDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T16:40:23Z"
    mac: ENC[AES256_GCM,data:wkXuuYp362NVCfSU+8uTMdfR66kyWGTJXQd9poYFkyvkaWVlsIaL7MiZxHuR3mVU0TCHsP0RzaBJ6l/auAuOwOrRH5KUSC5jToaAkcanBw+b2FVoETI/zLKgwqYqMP6PZQcd6fuQ+5uTD3SZkRM72AXnp0sSGZ0Ve/7rPODtsO4=,iv:b+y+6AS/rOiRYwDfrJL6zOw3uQEfnIsD0L2NOhXFMnE=,tag:c96/DV8OfPfm5HFbp1KQqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
