jellyfin_api_key: ENC[AES256_GCM,data:/TKG+aEErqo=,iv:jB87wss45gbvNdfgZ6dpDzK9jbrse+zXKoRJJl0cxEc=,tag:Ns3ZHGfwn4u4NXKOGT61PA==,type:str]
sonarr_api_key: ENC[AES256_GCM,data:w10VOQhWyJU=,iv:Ls3I1726OLYVzEnMU7xq0N6c3XdZxoC1GOJbhnbifmw=,tag:tz9g2KqKDpCNsgXOgy59lA==,type:str]
radarr_api_key: ENC[AES256_GCM,data:Qplz1FlVUfk=,iv:208opLXBDxD/0I4wTZKXrMr6Y3VIM3f4I/8UCUdynCE=,tag:oJhJ2V6Xh+cQ+uecu+UJlA==,type:str]
prowlarr_api_key: ENC[AES256_GCM,data:BxqGwqejTzc=,iv:jFBvWhQpbvCPyP3GLZKLgFUUDHjD1fzstIAkl3A2sGM=,tag:NIbGpi0IJIS9z2vX+ZHZUQ==,type:str]
qbittorrent_password: ENC[AES256_GCM,data:G4ZQt1Xs03Q=,iv:7p5XiWeIzy0s8w4zVRwHfbr+SVKSwtSSF3Fzds7kZZY=,tag:mAKIQzf69/1mvhz3n58fNw==,type:str]
sops:
    age:
        - recipient: age1sxza4f6jp9mmv3fhu0fw3j9gd0vfqvwchmn838kxcda5guq9yqqsprv538
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVUZGK0szT1l3U3dMNVZj
            ZTV2MllMYllwamlvU2JhZUpHOXg3WWRJZG04CjZxMnpCOGllUEgrZllUbHYvUkI3
            UkE2TGVETHRZU0htZk9PaFovOWxvemMKLS0tIHlkZStIa2w0Y2tnMHlDNGNiZGxZ
            bmd4V0sxTWgzclRtbmlyQ0pBR0J5ckEKcut212QElNlv9Tu2KgiR01OFiMcScco6
            aALy19fsLE+DpO9RlH/Chyluk2C6M68VxwTrQp4d62E9X8ndPHMORA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T11:07:43Z"
    mac: ENC[AES256_GCM,data:aTyq86oSWUH4OpjQBYgkksd7x7PTJWHYNzZfiurWhApoSzQ83HW623xmQWEf0p4i+fVfV6mjUoA9OykRXkT9BZJ9fhmDbSlEpNTuK3VSvWQHOUxZI4f26/oeXdAlZqbAtP1bTQZUSNaThzrJ9Yp4bLeqtqs2JL2twp6qoCKOaNk=,iv:nEv4j0ePsrOnvDniPV6VKWVEvZeg+muAC6k0DvA5pYc=,tag:lyMETwDTWjFN8rVIieAR9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
