services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=p4386889
      - OPENVPN_PASSWORD=81jR3hv*kVUbqaV^arIz@72BX
      - SERVER_REGIONS=Netherlands
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.20.0/24,192.168.40.0/24
      - UPDATER_PERIOD=24h
    volumes:
      - /data/gluetun:/gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "ping -c 1 1.1.1.1 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1
    container_name: qbittorrent
    network_mode: container:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - /data/qbittorrent/config:/config
      - /data/downloads:/data/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped


