services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/sonarr/config:/config
      - /data:/data  # Must match qBittorrent for hardlinks
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/radarr/config:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls20
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/lidarr/config:/config
      - /data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  bookshelf:
    image: ghcr.io/pennydreadful/bookshelf:hardcover-v0.4.20.129
    container_name: bookshelf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/bookshelf/config:/config
      - /data:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.5
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/bazarr/config:/config
      - /data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped

  subgen:
    image: mccloud/subgen:2026.02.9-cpu
    container_name: subgen
    environment:
      - WHISPER_MODEL=base
      - TRANSCRIBE_DEVICE=cpu
      - USE_PATH_MAPPING=True
      - MONITOR=/data/media
      - PROCADDEDMEDIA=True
      - PROCMEDIAONSTART=False
    volumes:
      - /data/subgen/config:/config
      - /data/subgen/log:/log
      - /data/media:/data/media
    ports:
      - 9000:9000
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Amsterdam
    ports:
      - 8191:8191
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:v0.8.3-ls240
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /data/mylar3/config:/config
      - /data:/data
    ports:
      - 8090:8090
    restart: unless-stopped
